### ISSUE TITLE
please help me install Kubernets, stuck at installation

### ISSUE THREAD

**Issue by anoopnm182** [rdrgporto/kubernetes-vagrant#1]
please see attached screenshots, shows  the work i have done
<img width="350" alt="1" src="https://user-images.githubusercontent.com/89909933/131653323-8d1d0695-c7a4-4e61-923e-b8e4aa117704.PNG">
<img width="525" alt="2" src="https://user-images.githubusercontent.com/89909933/131653329-f0bee83b-88ca-4940-973a-a39622acd1fe.PNG">
<img width="550" alt="3" src="https://user-images.githubusercontent.com/89909933/131653339-eadaa2fc-cd59-4896-9401-d258dd2dd516.PNG">

**Comment by rdrgporto** [comment]
Hi, @anoopnm182 

Have you used Vagrant? It seems a different installation.

Regards

**Comment by anoopnm182** [comment]
sorry, I am not a Linux guy. I got this ISO and installed the VM. How we can check whether its Vagrant or not? Is Vagrant wont support K8s?

**Comment by rdrgporto** [comment]
Hi, @anoopnm182 

You have to install [Vagrant](https://www.vagrantup.com/) and [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

Regards

**Comment by anoopnm182** [comment]
Do i need to install these on Ubuntu OS? This Ubuntu VM is running on a VMware esxi hosts

**Comment by rdrgporto** [comment]
Hi, @anoopnm182 

You can install Vagrant on Ubuntu OS: [Install Vagrant on Ubuntu 18.04](https://linuxize.com/post/how-to-install-vagrant-on-ubuntu-18-04/). Moreover, instead of using Vagrant, you can install Kubernetes in your Ubuntu: [Install Kubernetes on Ubuntu](https://www.virtualizationhowto.com/2021/07/setup-kubernetes-ubuntu-20-04-step-by-step-cluster-configuration/).

Regards

**Comment by anoopnm182** [comment]
i tried run "kubeadm init", but stuck below error.  Swap is off.  would you please help me.


**root@Kube-Master:~# kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=**
[init] Using Kubernetes version: v1.22.1
[preflight] Running pre-flight checks......
...................................................

 

[control-plane] Creating static Pod manifest for "kube-controller-manager"  
[control-plane] Creating static Pod manifest for "kube-scheduler"  
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"  
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s  
[kubelet-check] Initial timeout of 40s passed.  
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.  
[kubelet-check] It seems like the kubelet isn't running or healthy.  
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.  
[kubelet-check] It seems like the kubelet isn't running or healthy.  
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.  

 

Unfortunately, an error has occurred:  
                timed out waiting for the condition  
This error is likely caused by:  
                - The kubelet is not running  
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)  

 

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:  
- 'systemctl status kubelet'  
                - 'journalctl -xeu kubelet'  
Additionally, a control plane component may have crashed or exited when started by the container runtime.  
        To troubleshoot, list all containers using your preferred container runtimes CLI.  
Here is one example how you may list all Kubernetes containers running in docker:  
- 'docker ps -a | grep kube | grep -v pause'  
                Once you have found the failing container, you can inspect its logs with:  
                - 'docker logs CONTAINERID'  

 

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster  
To see the stack trace of this error execute with --v=5 or higher  

 

**root@Kube-Master:~# sudo systemctl restart kubelet.service  
root@Kube-Master:~# sudo systemctl status kubelet**  
● kubelet.service - kubelet: The Kubernetes Node Agent  
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)  
    Drop-In: /etc/systemd/system/kubelet.service.d  
             └─10-kubeadm.conf  
Active: activating (auto-restart) (Result: exit-code) since Mon 2021-09-06 03:19:50 UTC; 3s ago  
       Docs: https://kubernetes.io/docs/home/  
    Process: 4827 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS  
 $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/>   
   Main PID: 4827 (code=exited, status=1/FAILURE)  

 

Sep 06 03:19:50 Kube-Master systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE  
Sep 06 03:19:50 Kube-Master systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by rdrgporto** [comment]
Hi, @anoopnm182 

Please try https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md for questions and support.

Thanks,

Regards
